#!/usr/bin/env python3
"""Collection insights → INSIGHTS.md.

A read-only stats report over the scored collection: grade distributions, healthiest
cuisines, best fatty-liver picks, biggest "quick-win" improvements, and protein/calorie
standouts. Regenerated by run_all.sh; viewable on GitHub.
"""
import os, json
from collections import Counter, defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(REPO, 'data')

def load(f):
    return {r['id']: r for r in json.load(open(os.path.join(DATA, f)))['recipes']}

idx = load('index.json')
nut = load('recipe_nutrition.json')
imp = load('recipe_improvements.json')

# in-scope, real dishes only for most stats
real = {i: r for i, r in idx.items()
        if not r['flags'].get('out_of_scope') and not r['flags'].get('non_food')}

def grade_line(counts, order):
    tot = sum(counts.values()) or 1
    return ' · '.join(f'{g} {counts.get(g,0)}' for g in order)

def avg(xs):
    xs = [x for x in xs if x is not None]
    return round(sum(xs) / len(xs), 1) if xs else 0

L = ['# 📊 Collection Insights\n',
     f'*Auto-generated by `scripts/build_insights.py` over {len(idx)} recipes '
     f'({len(real)} in-scope). Educational estimates, not medical advice.*\n']

# ---- overview ----
med_g = Counter(r['mediterranean']['grade'] for r in real.values() if r.get('mediterranean'))
liv_g = Counter(r['fatty_liver']['grade'] for r in real.values() if r.get('fatty_liver'))
nut_g = Counter((r['nutrition'] or {}).get('nutri_score') for r in real.values() if r.get('nutrition'))
L.append('## Overview\n')
L.append(f"- **Mediterranean:** {grade_line(med_g,'ABCDF')}  ·  avg "
         f"{avg([r['mediterranean']['score'] for r in real.values() if r.get('mediterranean')])}/100")
L.append(f"- **Fatty-Liver:** {grade_line(liv_g,'ABCDF')}  ·  avg "
         f"{avg([r['fatty_liver']['score'] for r in real.values() if r.get('fatty_liver')])}/100")
L.append(f"- **Nutri-Score:** {grade_line(nut_g,'ABCDE')}")
L.append(f"- **Median calories/serving:** "
         f"{sorted([(r['nutrition'] or {}).get('kcal') or 0 for r in real.values()])[len(real)//2]} kcal\n")

# ---- healthiest cuisines (by avg fatty-liver score, min 4 recipes) ----
by_cui = defaultdict(list)
for r in real.values():
    c = r.get('cuisine') or 'Unspecified'
    if r.get('fatty_liver'):
        by_cui[c].append(r['fatty_liver']['score'])
rows = sorted(((c, avg(v), len(v)) for c, v in by_cui.items() if len(v) >= 4 and c != 'Unspecified'),
              key=lambda x: -x[1])
L.append('## Healthiest cuisines (avg Fatty-Liver score, ≥4 recipes)\n')
L.append('| Cuisine | Avg | Recipes |')
L.append('|---|--:|--:|')
for c, a, n in rows[:10]:
    L.append(f'| {c} | {a} | {n} |')
L.append('')

# ---- best fatty-liver mains ----
mains = [r for r in real.values() if r.get('fatty_liver') and r.get('dish_type') in ('main', 'soup/stew')]
mains.sort(key=lambda r: -r['fatty_liver']['score'])
L.append('## Best fatty-liver mains & soups\n')
L.append('| Recipe | Liver | Med | kcal |')
L.append('|---|:--:|:--:|--:|')
for r in mains[:12]:
    L.append(f"| {r['name']} | {r['fatty_liver']['grade']} ({r['fatty_liver']['score']}) | "
             f"{r['mediterranean']['grade']} | {(r['nutrition'] or {}).get('kcal') or '—'} |")
L.append('')

# ---- biggest quick-wins (improvement delta) ----
wins = []
for i, r in real.items():
    im = imp.get(i)
    if im and im.get('delta', 0) >= 15:
        wins.append((idx[i]['name'], im['delta'], idx[i]['mediterranean']['grade'],
                     im.get('improved_grade'), (im.get('swaps') or [''])[0]))
wins.sort(key=lambda x: -x[1])
L.append('## Biggest "quick-win" improvements (≤3 Mediterranean swaps)\n')
L.append('| Recipe | Gain | Grade | Top swap |')
L.append('|---|--:|:--:|---|')
for name, d, g0, g1, swap in wins[:12]:
    L.append(f'| {name} | +{d} | {g0}→{g1} | {swap[:52]} |')
L.append('')

# ---- protein / lightest standouts ----
def kcal(i): return (idx[i]['nutrition'] or {}).get('kcal') or 0
def prot(i): return ((nut.get(i) or {}).get('per_serving') or {}).get('protein_g') or 0
hp = sorted((i for i in real if kcal(i)), key=lambda i: -prot(i))[:8]
light = sorted((i for i in real if kcal(i) and idx[i].get('dish_type') in ('main', 'soup/stew', 'salad')),
               key=lambda i: kcal(i))[:8]
L.append('## Standouts\n')
L.append('**Highest protein/serving:** ' + ' · '.join(f'{idx[i]["name"]} ({round(prot(i))}g)' for i in hp))
L.append('')
L.append('**Lightest mains/soups/salads:** ' + ' · '.join(f'{idx[i]["name"]} ({kcal(i)} kcal)' for i in light))
L.append('')

# ---- dish types ----
dt = Counter(r.get('dish_type') for r in real.values())
L.append('## Dish types\n' + ' · '.join(f'{k}: {v}' for k, v in dt.most_common()) + '\n')

open(os.path.join(REPO, 'INSIGHTS.md'), 'w', encoding='utf-8').write('\n'.join(L))
print(f'Wrote INSIGHTS.md — {len(real)} in-scope recipes, {len(rows)} cuisines, {len(wins)} quick-wins')
